name: defensefinder
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - hmmer=3.4
  - icu=78.2
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.14.2
  - python_abi=3.14
  - readline=8.3
  - tk=8.6.13
  - zstd=1.5.7
  - pip:
      - archspec==0.2.5
      - certifi==2026.1.4
      - click==8.0.3
      - colorama==0.4.6
      - colorlog==6.3.0a1
      - macsyfinder==2.1.4
      - mdmparis-defense-finder==2.0.1
      - networkx==3.6.1
      - numpy==2.4.1
      - packaging==25.0
      - pandas==2.3.3
      - psutil==7.2.1
      - pyhmmer==0.11.4
      - pyrodigal==3.7.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - six==1.17.0
      - tzdata==2025.3
prefix: /home/marco/miniconda3/envs/defensefinder
