name: genomad
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.3.1
  - aom=3.9.1
  - aragorn=1.2.41
  - archspec=0.2.5
  - aria2=1.37.0
  - astunparse=1.6.3
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - dav1d=1.2.1
  - flatbuffers=24.3.25
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gast=0.7.0
  - gawk=5.3.1
  - genomad=1.11.2
  - giflib=5.2.2
  - gmp=6.3.0
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.74.1
  - h2=4.3.0
  - h5py=3.15.1
  - harfbuzz=10.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - joblib=1.5.3
  - jpeg=9e
  - keras=3.12.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250814.1
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.18.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.53
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxgboost=3.1.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvmlite=0.46.0
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - ml_dtypes=0.5.4
  - mmseqs2=18.8cc5c
  - mpfr=4.2.1
  - namex=0.1.0
  - ncurses=6.5
  - numba=0.63.1
  - numpy=2.1.3
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - optree=0.18.0
  - packaging=25.0
  - pcre2=10.47
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - protobuf=6.33.0
  - pthread-stubs=0.4
  - py-xgboost=3.1.2
  - pygments=2.19.2
  - pyrodigal=3.7.0
  - pyrodigal-gv=0.3.2
  - pysocks=1.7.1
  - python=3.13.11
  - python-crfsuite=0.9.12
  - python-flatbuffers=24.3.25
  - python_abi=3.13
  - rav1e=0.7.1
  - re2=2025.11.05
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - rich-click=1.9.5
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.1
  - svt-av1=3.1.2
  - taxopy=0.14.0
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.20.0
  - tensorflow-base=2.20.0
  - termcolor=3.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - werkzeug=3.1.5
  - wrapt=2.0.1
  - xgboost=3.1.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /home/marco/miniconda3/envs/genomad
