local-cores: 1
cores: 1
use-conda: true
executor: "slurm"
latency-wait: 30
jobs: 15
default-resources:
  mem_mb: 16000
  slurm_extra: "'--qos=30min'"
  runtime: 29m
set-resources:
  genomad_run:
    mem_mb: 60000
    cpus_per_task: 4